name: realtime_collaborative_whiteboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.2
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  share_plus: ^10.1.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
